import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  // Create story templates
  const templates = [
    {
      title: 'The Space Adventure',
      description: 'Join an exciting journey through the solar system, discovering planets and meeting friendly aliens',
      category: 'space',
      minAge: 5,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page space adventure story where {childName}, a {childAge}-year-old explorer, embarks on a journey through the solar system. The story should include educational facts about planets while maintaining an exciting narrative. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Vibrant space scenes with colorful planets, stars, and friendly alien characters. Style should be engaging and age-appropriate, suitable for children aged 5-14.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'The Magical Forest',
      description: 'Explore an enchanted forest filled with talking animals and hidden treasures',
      category: 'fantasy',
      minAge: 3,
      maxAge: 12,
      pageCount: 15,
      promptTemplate: `Write a 15-page fantasy story where {childName}, a {childAge}-year-old child, discovers a magical forest near their home. The forest has talking animals, magical creatures, and teaches lessons about friendship and courage. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Whimsical forest scenes with vibrant colors, friendly animals, and magical elements. Age-appropriate style preferred.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Ocean Explorer',
      description: 'Dive deep into the ocean to discover marine life and underwater mysteries',
      category: 'adventure',
      minAge: 4,
      maxAge: 13,
      pageCount: 15,
      promptTemplate: `Write a 15-page underwater adventure where {childName}, a {childAge}-year-old marine explorer, discovers the wonders of the ocean. Include educational elements about sea creatures and ocean conservation. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Beautiful underwater scenes with colorful coral reefs, friendly fish, dolphins, and sea turtles. Bright, inviting blue tones. Age-appropriate complexity.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'The Brave Knight',
      description: 'Become a knight on a quest to help the kingdom and learn about bravery',
      category: 'adventure',
      minAge: 5,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page medieval adventure where {childName}, a {childAge}-year-old brave knight, goes on a quest to help their kingdom. The story should emphasize courage, kindness, and problem-solving. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Medieval castle scenes with knights, dragons (friendly), and kingdom landscapes. Vibrant colors with age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'The Animal Rescue',
      description: 'Help rescue and care for animals while learning about different species',
      category: 'animals',
      minAge: 3,
      maxAge: 12,
      pageCount: 15,
      promptTemplate: `Write a 15-page story where {childName}, a {childAge}-year-old animal lover, helps rescue and care for different animals. Include educational facts about animal care and habitats. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Warm, caring scenes with various animals in need of help. Realistic but child-friendly depictions of animals and natural settings. Age-appropriate complexity.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'The Time Traveler',
      description: 'Travel through time to visit different historical periods and meet famous figures',
      category: 'adventure',
      minAge: 7,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page time travel adventure where {childName}, a {childAge}-year-old time traveler, journeys through different historical periods. Include educational elements about history and significant events. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Historical scenes from different time periods with accurate period details. Vibrant colors and engaging compositions. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Mystery Detective',
      description: 'Solve exciting mysteries as a junior detective using observation and logic',
      category: 'mystery',
      minAge: 6,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page mystery story where {childName}, a {childAge}-year-old detective, solves an intriguing mystery using observation, logic, and problem-solving skills. Include age-appropriate clues and puzzles. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Detective scenes with clues, magnifying glasses, and mysterious settings. Engaging visual storytelling with age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Robot Friend',
      description: 'Build and befriend a robot companion in a futuristic world',
      category: 'science-fiction',
      minAge: 5,
      maxAge: 13,
      pageCount: 15,
      promptTemplate: `Write a 15-page science fiction story where {childName}, a {childAge}-year-old inventor, builds a robot friend. Explore themes of friendship, technology, and creativity. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Futuristic settings with friendly robots, technology, and innovative designs. Bright, optimistic sci-fi aesthetic. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Jungle Explorer',
      description: 'Trek through the jungle discovering exotic animals and ancient ruins',
      category: 'adventure',
      minAge: 5,
      maxAge: 12,
      pageCount: 15,
      promptTemplate: `Write a 15-page jungle adventure where {childName}, a {childAge}-year-old explorer, discovers exotic animals and learns about rainforest conservation. Include educational elements about wildlife and ecosystems. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Lush jungle scenes with vibrant plants, exotic animals, and adventure settings. Rich greens and natural tones. Age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Sports Champion',
      description: 'Train hard and compete in your favorite sport to become a champion',
      category: 'sports',
      minAge: 6,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page sports story where {childName}, a {childAge}-year-old athlete, trains and competes in their favorite sport. Emphasize teamwork, perseverance, and sportsmanship. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Dynamic sports action scenes with energy and movement. Bright, motivational imagery. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Music Star',
      description: 'Discover musical talent and perform on stage in a magical musical journey',
      category: 'music',
      minAge: 4,
      maxAge: 12,
      pageCount: 15,
      promptTemplate: `Write a 15-page musical story where {childName}, a {childAge}-year-old musician, discovers their musical talents and performs. Explore themes of creativity, practice, and self-expression. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Musical scenes with instruments, stages, and vibrant performances. Colorful and energetic compositions. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Art Adventure',
      description: 'Enter magical paintings and meet famous artists while creating masterpieces',
      category: 'arts',
      minAge: 5,
      maxAge: 13,
      pageCount: 15,
      promptTemplate: `Write a 15-page art adventure where {childName}, a {childAge}-year-old artist, enters magical paintings and explores different art styles. Include educational elements about art history and creativity. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Artistic scenes in various painting styles with creative, colorful imagery. Inspired by famous artworks. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Superhero Origin',
      description: 'Discover superpowers and learn to be a hero who helps others',
      category: 'superhero',
      minAge: 5,
      maxAge: 12,
      pageCount: 15,
      promptTemplate: `Write a 15-page superhero origin story where {childName}, a {childAge}-year-old, discovers superpowers and learns to be a hero. Emphasize responsibility, helping others, and using powers wisely. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Dynamic superhero scenes with action, colorful costumes, and heroic poses. Comic book inspired with age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'The Lost City',
      description: 'Uncover an ancient lost city and learn about past civilizations',
      category: 'adventure',
      minAge: 7,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page archaeological adventure where {childName}, a {childAge}-year-old explorer, discovers a lost ancient city. Include educational elements about archaeology and ancient civilizations. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Ancient ruins, temples, and archaeological discoveries with mysterious atmosphere. Detailed and adventurous. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Farm Friends',
      description: 'Help run a farm and care for all the animals while learning about agriculture',
      category: 'animals',
      minAge: 2,
      maxAge: 8,
      pageCount: 15,
      promptTemplate: `Write a 15-page farm story where {childName}, a {childAge}-year-old, helps on a farm and cares for animals. Include educational elements about farm life, agriculture, and animal care. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Warm farm scenes with friendly animals, barns, fields, and pastoral settings. Bright, cheerful colors. Age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Weather Wizard',
      description: 'Control the weather and learn about meteorology and natural phenomena',
      category: 'science',
      minAge: 6,
      maxAge: 13,
      pageCount: 15,
      promptTemplate: `Write a 15-page science adventure where {childName}, a {childAge}-year-old weather wizard, learns to understand and work with weather patterns. Include educational elements about meteorology and climate. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Weather phenomena with clouds, rain, snow, sunshine, and atmospheric effects. Dramatic and educational. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Monster Friends',
      description: 'Meet friendly monsters and learn that being different is wonderful',
      category: 'fantasy',
      minAge: 3,
      maxAge: 9,
      pageCount: 15,
      promptTemplate: `Write a 15-page fantasy story where {childName}, a {childAge}-year-old, befriends misunderstood monsters. Explore themes of acceptance, diversity, and kindness. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Friendly, colorful monsters in whimsical settings. Fun, non-scary monster designs. Bright, inviting colors. Age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Island Castaway',
      description: 'Survive and thrive on a deserted island using resourcefulness and creativity',
      category: 'adventure',
      minAge: 7,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page survival adventure where {childName}, a {childAge}-year-old, is stranded on a beautiful island and must use creativity and problem-solving to thrive. Emphasize resourcefulness and nature appreciation. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Tropical island scenes with beaches, palm trees, ocean views, and nature. Beautiful, adventurous atmosphere. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Circus Adventure',
      description: 'Join the circus and learn amazing performance skills while traveling the world',
      category: 'adventure',
      minAge: 4,
      maxAge: 11,
      pageCount: 15,
      promptTemplate: `Write a 15-page circus story where {childName}, a {childAge}-year-old performer, joins a traveling circus and learns performance skills. Emphasize practice, teamwork, and entertaining others. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Colorful circus scenes with performers, big tops, acts, and entertainment. Vibrant, energetic atmosphere. Age-appropriate style.',
      includesPets: true,
      includesInterests: true,
      isActive: true,
    },
    {
      title: 'Space Station',
      description: 'Live on a space station orbiting Earth and conduct exciting experiments',
      category: 'science-fiction',
      minAge: 6,
      maxAge: 14,
      pageCount: 15,
      promptTemplate: `Write a 15-page space station story where {childName}, a {childAge}-year-old astronaut, lives on a space station and conducts experiments. Include educational elements about space, science, and living in orbit. Adjust complexity and vocabulary based on the child's age.`,
      imageStyleGuide: 'Futuristic space station interiors and exteriors with Earth views, astronauts, and space technology. Realistic sci-fi aesthetic. Age-appropriate style.',
      includesPets: false,
      includesInterests: true,
      isActive: true,
    },
  ];

  for (const template of templates) {
    await prisma.storyTemplate.upsert({
      where: { title: template.title },
      update: template,
      create: template,
    });
    console.log(`Created template: ${template.title}`);
  }

  console.log('Seeding completed!');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
